#!/usr/bin/env bash

set -eux

function install_python(version) {
	pyenv install $version
	pyenv global $version
}

# Is pyenv command exists?
if ! type pyenv > /dev/null 2>&1; then
	curl https://pyenv.run | bash # Install pyenv
	echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
	echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
	echo 'eval "$(pyenv init -)"' >> ~/.bashrc
	export PYENV_ROOT="$HOME/.pyenv"
	command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
	eval "$(pyenv init -)"
	install_python(3.9.9)
fi

# Is python3 command exists?
if ! type python3 > /dev/null 2>&1; then
	install_python(3.9.9)
fi

python3 -m pip install --upgrade pip
python3 -m pip install fprettify fortls black flake8
