#!/usr/bin/env bash

set -eux
# Is pyenv command exists?
if ! type pyenv > /dev/null 2>&1; then
	curl https://pyenv.run | bash # Install pyenv
	exec $SHELL -l # Reload shell
	pyenv install 3.9.9
	pyenv install 2.7.18
	pyenv global 3.9.9 2.7.18
fi

python -m pip install --upgrade pip
python -m pip install fprettify fortls black flake8
